name: waporact
channels:
  - defaults
dependencies:
  - gdal>=3.0.2
  #- matplotlib>=3.3.*
  - notebook>=6.1.*
  - numpy>=1.19.*
  - pandas>=1.1.*
  - geopandas>=0.9.*
  - fiona>=1.8.13
  - pyproj>=2.6.1
  - pip>=20.2.2=py37_0
  - python>=3.7
  - shapely>=1.6.*
  - requests>=2.24.*
  - rtree>=0.9.3
  - rasterio
  - openpyxl
  - parse
  - plotly
  - python-kaleido


